### ISSUE TITLE
Failed to Create Build in Teamcity (5.4.0)

### ISSUE THREAD

**Issue by papymaj5** [OctopusDeploy/Octopus-TeamCity#38]
Updated to 5.4.0 this morning and got this error when trying to run builds in  TeamCity 2019.1.4:

> [2019-10-31 09:56:33,304]   WARN - rverSide.impl.RunningBuildImpl - Error while creating an AgentBuild
> java.lang.NullPointerException
> 	at octopus.teamcity.server.OctopusBuildInformationBuildStartProcessor.updateParameters(OctopusBuildInformationBuildStartProcessor.java:49)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.prepareRunners(RunningBuildImpl.java:81)
> 	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.createAgentBuild(RunningBuildImpl.java:393)
> 	at jetbrains.buildServer.serverSide.impl.BuildStarter.startBuild(BuildStarter.java:55)
> 	at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$null$0(BuildStarter.java:184)
> 	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
> 	at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$startBuildAsync$1(BuildStarter.java:2)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Reverting to 5.3.0 fixed the problem.

**Comment by matt-richardson** [comment]
Sorry to see you've hit this issue, @papymaj5.

Can you let us know a bit more info about your setup? Are you using git? Did the build in question run against a branch?

Looks like the issue is steming from [this line](https://github.com/OctopusDeploy/Octopus-TeamCity/blob/master/octopus-server/src/main/java/octopus/teamcity/server/OctopusBuildInformationBuildStartProcessor.java#L49) where we're getting the branch for a given build. Looking at [the docs](http://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildPromotion.html#getBranch--), it appears it can be null in some circumstances. It's just not clear what circumstances they are...
